CREATE USER MROJAS IDENTIFIED BY maquina1;
GRANT CREATE SESSION TO MROJAS;
--CONNECT MROJAS/maquina1
CREATE USER ZSALINAS IDENTIFIED BY persona1;
GRANT CREATE SESSION TO ZSALINAS;

CREATE USER ARAMIREZ IDENTIFIED BY persona2;
GRANT CREATE SESSION TO ARAMIREZ;

CREATE USER XCORTEZ IDENTIFIED BY persona3;
GRANT CREATE SESSION TO XCORTEZ;

CREATE USER FLOPEZ IDENTIFIED BY persona4;
GRANT CREATE SESSION TO FLOPEZ;

CREATE USER JCHAVEZ IDENTIFIED BY persona5;
GRANT CREATE SESSION TO JCHAVEZ;

CREATE USER RPEREZ IDENTIFIED BY persona6;
GRANT CREATE SESSION TO RPEREZ;

CREATE USER LORTIZ IDENTIFIED BY persona7;
GRANT CREATE SESSION TO LORTIZ;

CREATE USER OGONZALE IDENTIFIED BY persona8;
GRANT CREATE SESSION TO OGONZALE;

CREATE USER TNOLASCO IDENTIFIED BY persona9;
GRANT CREATE SESSION TO TNOLASCO;
