SELECT NAME AS NOMBRE_EMPLEADO, 
		    EMPLOYEE_ID,
		    HIRE_DATE, 
		    JOB_ID, 
		    MIN_SALARY, 
		    SALARY 
FROM EMPLOYEES 
INNER JOIN JOB_HISTORY USING (EMPLOYEE_ID) 
INNER JOIN JOBS USING (JOB_ID);


SELECT FIRST_NAME, SALARY, SALARY*0.052 IMSS
FROM EMPLOYEES
WHERE SALARY < 2700;

SELECT FIRST_NAME, SALARY, SALARY*0.04 INFONAVIT
FROM EMPLOYEES
WHERE SALARY BETWEEN 10000 AND 18000;

SELECT FIRST_NAME, SALARY SALARIO_BRUTO, SALARY*0.052 IMSS, SALARY*0.04 INFONAVIT, SALARY*0.28 ISR, SALARY-((SALARY*0.052)+(SALARY*0.04)+(SALARY*0.28)) SALARIO_NETO
FROM EMPLOYEES
WHERE SALARY < 2700;

SELECT FIRST_NAME, SALARY SALARIO_BRUTO, SALARY*0.052 IMSS, SALARY*0.04 INFONAVIT, SALARY*0.28 ISR, SALARY-((SALARY*0.052)+(SALARY*0.04)+(SALARY*0.28)) SALARIO_NETO
FROM EMPLOYEES
WHERE SALARY BETWEEN 10000 AND 18000;

SELECT FIRST_NAME, SALARY/2 SALARIO_BRUTO, SALARY*0.052 IMSS, SALARY*0.04 INFONAVIT, SALARY*0.28 ISR, (SALARY-((SALARY*0.052)+(SALARY*0.04)+(SALARY*0.28)))/2 SALARIO_NETO
FROM EMPLOYEES
WHERE SALARY BETWEEN 100

SELECT FIRST_NAME||’ ‘||LAST_NAME EMPLEADO,
    SALARY/2 SALARIO_BRUTO,
    SALARY*0.052 IMSS,
    SALARY*0.04 INFONAVIT,
    SALARY*0.28 ISR,
    (SALARY-((SALARY*0.052)+(SALARY*0.04)+(SALARY*0.28)))/2 SALARIO_NETO
	FROM EMPLOYEES
	WHERE SALARY BETWEEN 10000 AND 15000
	ORDER BY 6, 1;

COLUMN EMPLEADO FORMAT A20
COLUMN SALARIO_BRUTO FORMAT $999,999.99
COLUMN SALARIO_NETO FORMAT $999,999.99
COLUMN IMSS FORMAT $99,999.99
COLUMN INFONAVIT FORMAT $99,999.99
COLUMN ISR FORMAT $99,999.99
COLUMN EMPLEADO FORMAT A12
COLUMN EMPLEADO FORMAT A20

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, 
	 SALARY,
     SALARY/2 SAL_BRUTO,
     SALARY*0.052 IMSS,
     SALARY*0.04 INFONAVIT,
     SALARY*0.28 ISR,
     (SALARY-((SALARY*0.052)+(SALARY*0.04)+(SALARY*0.28)))/2 SAL_NETO
  FROM EMPLOYEES
  WHERE SALARY BETWEEN 10000 AND 15000
  ORDER BY 6,1


CREATE TABLE LOS_BONITOS
    AS SELECT FIRST_NAME||’ ‘||LAST_NAME EMPLEADO,
                        SALARY SALARIO, EMAIL
    FROM EMPLOYEES
    WHERE SALARY < 3000;


SELECT * FROM LOS_BONITOS;
ALTER TABLE LOS_BONITOS
	MODIFY EMPLEADO VARCHAR2(25);

ALTER TABLE LOS_BONITOS
	MODIFY EMPLEADO VARCHAR2(18);

CREATE VIEW LAS_BONITAS AS
	SELECT FIRST_NAME NOMBRE,
		LAST_NAME APELLIDO,
		SALARY SAL_BRUTO,
		SALARY*0.052 IMSS,
		SALARY*0.04 INFONAVIT,
		SALARY*0.28 ISR
	FROM EMPLOYEES;

SELECT NOMBRE||''||APELLIDO EMPLEADO,
                 SAL_BRUTO/2 SALARIO_QUINCENAL,
                 (IMSS+INFONAVIT+ISR)/2 DEDUCCIONES,
                 SAL_BRUTO-(IMSS+INFONAVIT+ISR) SALARIO_NETO
    FROM LAS_BONITAS
    ORDER BY 4 DESC;

 CREATE VIEW ONDE_ANDAN AS
    SELECT FIRST_NAME||’ ‘||LAST_NAME TRABAJADOR,
                  DEPARTMENT_NAME DEPARTAMENTO,
                  CITY CIUDAD,
                  COUNTRY_NAME PAIS,
                  REGION_NAME REGION
     FROM EMPLOYEES A,
                DEPARTMENTS B,
                LOCATIONS C,
                               COUNTRIES D,
                                REGIONS E
                    WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
                    AND      B.LOCATION_ID  = C.LOCATION_ID
                    AND      C.COUNTRY_ID = D.COUNTRY_ID
                    AND      D.REGION_ID = E.REGION_ID
                    AND      SALARY < 15000;

--TareaConsultas

CREATE VIEW EmpleadoCargo AS
	SELECT LAST_NAME ||' '|| FIRST_NAME "Nombre Completo",
	       DEPARTMENT_NAME Departamento,
	       SALARY Salario,
	       HIRE_DATE "Fecha Ingreso"
			FROM EMPLOYEES 
			JOIN DEPARTMENTS 
			USING(DEPARTMENT_ID)
		ORDER BY 1, 2

CREATE OR REPLACE VIEW EmpleadoCargoSH AS
		SELECT LAST_NAME ||' '|| FIRST_NAME "Nombre Completo",
		       DEPARTMENT_NAME Departamento,
		       SALARY Salario
				FROM EMPLOYEES 
				JOIN DEPARTMENTS 
				USING(DEPARTMENT_ID)
			ORDER BY 1, 2

SELECT LAST_NAME||' '||FIRST_NAME AS "Nombre Completo", SALARY AS Salario, HIRE_DATE AS "FechaIngreso"
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'R%'
AND SALARY > 3000;
