SELECT FIRST_NAME||’ ‘||LAST_NAME EMPLEADO, 
	SALARY SALARIO
FROM EMPLOYEES
ORDER BY 2 DESC

SELECT FIRST_NAME||’ ‘||LAST_NAME EMPLEADO,
CASE SALARY WHEN 3100 THEN ‘Bajo’
WHEN 10000 THEN ‘Alto’
ELSE ‘Medio Medio’ END
EMPLOYEES;

SELECT FIRST_NAME||’ ‘||LAST_NAME EMPLEADO,
    CASE SALARY WHEN 3100 THEN ‘Bajo’
    WHEN 10000 THEN ‘Alto’
    ELSE ‘Medio Medio’ END
    FROM EMPLOYEES;

SELECT FIRST_NAME||’ ‘||LAST_NAME EMPLEADO, SALARY SALARIO
   FROM EMPLOYEES;

 SELECT FIRST_NAME||’ ‘||LAST_NAME EMPLEADO,
                    SALARY SUELDOS,
     CASE SALARY WHEN 2100 THEN ‘Bajo’
     WHEN 24000 THEN ‘Alto’
     ELSE ‘Medio’ END
     FROM EMPLOYEES;

SELECT FIRST_NAME||’ ‘||LAST_NAME EMPLEADO,
         SALARY SUELDOS,
         CASE SALARY WHEN 2100 THEN ‘Bajo’
WHEN 24000 THEN ‘Alto’
ELSE ‘Medio’ END    FROM EMPLOYEES
SELECT AVG(CASE WHEN e.salary > 2000 THEN e.salary    ELSE 2000 END) “Salario “Promedio
   employees e;

SELECT AVG(CASE WHEN e.salary > 2000 THEN e.salary    ELSE 2000 END) “Salario Promedio”
employees e;

SELECT AVG(SALARY) PROMEDIO FROM EMPLOYEES

SELECT AVG(SALARY) PROMEDIO FROM EMPLOYEES
   WHERE SALARY > 5000

SELECT COUNT(SALARY) FROM EMPLOYEES
    WHERE SALARY > 5000;

SELECT COUNT(SALARY) FROM EMPLOYEES
    WHERE SALARY > 5000;

SELECT COUNT(SALARY) FROM EMPLOYEES
    WHERE SALARY <= 5000;

SELECT AVG(SUM(SALARY)+(49*2000))
    FROM EMPLOYEES
    WHERE SALARY > 5000;

SELECT FIRST_NAME, SALARY, COMMISSION_PCT
     FROM EMPLOYEES
     WHERE DEPARTMENT_ID = 30;

SELECT FIRST_NAME||’ ‘||LAST_NAME TRABAJADOR,
                         SALARY SALARIO,
                         NVL(COMMISSION_PCT, 0)*(SALARY*12) COMISION
     FROM EMPLOYEES
     WHERE DEPARTMENT_ID = 30
     ORDER BY 3 DESC;
 SELECT FIRST_NAME||’ ‘||LAST_NAME TRABAJADOR,
                         SALARY SALARIO,
                         NVL(COMMISSION_PCT, 0)*(SALARY*12) COMISION
     FROM EMPLOYEES
     ORDER BY 3 DESC;
COLUMN SALARIO FORMAT $999,999.99

COLUMN COMISION FORMAT $999,999.99

COLUMN TRABAJADOR FORMAT A18
SELECT SUM(SALARY)
      FROM EMPLOYEES;
SELECT SUM(NVL(COMMISSION_PCT, 0)*(SALARY*12))
     FROM EMPLOYEES;

SELECT FIRST_NAME, SUM(SALARY)
   2      FROM EMPLOYEES;

SQL> SELECT DEPARTMENT_ID
   2      FROM EMPLOYEES
   3      ORDER BY 1;

SELECT DEPARTMENT_ID,
   2                    SUM(SALARY) TOTAL_SALARIOS,
   3                    AVG(SALARY) PROMEDIO_SALARIOS
   4      FROM EMPLOYEES
   5      GROUP BY DEPARTMENT_ID;

SELECT JOB_ID,
   2                    SUM(SALARY) TOTAL_SALARIOS,
   3                    AVG(SALARY) PROMEDIO_SALARIOS
   4      FROM EMPLOYEES
   5      GROUP BY JOB_ID
   6      ORDER BY 1;

   SELECT MANAGER_ID,
   2                    SUM(SALARY) TOTAL_SALARIOS,
   3                    AVG(SALARY) PROMEDIO_SALARIOS
   4      FROM EMPLOYEES
   5      GROUP BY MANAGER_ID
   6      ORDER BY 1;
SQL> SELECT SALARY,
   2                    SUM(SALARY) TOTAL_SALARIOS,
   3                    AVG(SALARY) PROMEDIO_SALARIOS,
   4                    COUNT(EMPLOYEE_ID) TRABAJADORES
   5      FROM EMPLOYEES
   6      GROUP BY SALARY
   7      ORDER BY 1;
SQL> SELECT MANAGER_ID,
   2                    SUM(SALARY) TOTAL_SALARIOS,
   3                    AVG(SALARY) PROMEDIO_SALARIOS,
   4                    COUNT(EMPLOYEE_ID) TRABAJADORES
   5      FROM EMPLOYEES
   6      GROUP BY MANAGER_ID
   7      ORDER BY 1;
SQL> SELECT MANAGER_ID,
   2                    SUM(SALARY) TOTAL_SALARIOS,
   3                    AVG(SALARY) PROMEDIO_SALARIOS,
   4                    COUNT(EMPLOYEE_ID) TRABAJADORES
   5      FROM EMPLOYEES
   6      GROUP BY MANAGER_ID
   7      ORDER BY 4 DESC;

SELECT DEPARTMENT_ID, JOB_ID, COUNT(EMPLOYEE_ID)
   2      FROM EMPLOYEES
   3      GROUP BY DEPARTMENT_ID, JOB_ID
   4      ORDER BY 1, 2;
