CREATE TABLESPACE USERS02 DATAFILE 'C:\data18c\oradata\ORCL\TEMP02.DAT' SIZE 51200K;


CREATE  USER  NOMBRE_USUARIO  IDENTIFIED  BY  CONTRASEÑA  DEFAULT  TABLESPACE USERS02

alter session set “_ORACLE_SCRIPT”=true;
CREATE USER EMPRESARIO IDENTIFIED BY CURSO DEFAULT TABLESPACE USERS03;


GRANT  CREATE  SESSION,  CREATE  TABLE,  CREATE  VIEW,  CREATE  ANY INDEX, CONNECT, RESOURCE, CREATE SEQUENCE, CREATE TYPE TO NOMBRE_USUARIO;

GRANT CREATE SESSION, CREATE TABLE,  CREATE VIEW,  CREATE ANY INDEX, CONNECT, RESOURCE, CREATE SEQUENCE, CREATE TYPE TO CURSO;

CONNECT  NOMBRE_USUARIO/CONTRASEÑA

SELECT TABLE_NAME FROM USER_TABLES;


error al editar 
GRANT UNLIMITED TABLESPACE TO <username>

SPOOL "NOMBRE" En SQLPLUS

SELECT LAST_NAME ||' '|| FIRST_NAME EMPLEADO,
       DEPARTMENT_NAME DEPARTAMENTO,
       SALARY SAL_MENSUAL
FROM EMPLOYEES JOIN DEPARTMENTS USING(DEPARTMENT_ID)
WHERE SALARY > 12000
ORDER BY 1, 2
--Ver contraints
SELECT *
  FROM user_constraints
 WHERE table_name = 'nominanueva'
   AND constraint_name = '<your constraint name>';

   SELECT DEPARTMENT_NAME DEPARTAMENTO,
                 FIRST_NAME||’ ‘||LAST_NAME TRABAJADOR,
                 JOB_TITLE PUESTO, 
                 E.FIRST_NAME||’ ‘||E.LAST_NAME JEFAZO
      FROM EMPLOYEES, DEPARTMENTS, JOBS, EMPLOYEES E
      WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
   AND EMPLOYEES.JOB_ID = JOBS.JOB_ID
   AND EMPLOYEES.MANAGER_ID = E.EMPLOYEE_ID
   ORDER BY 2, 1, 4;

SELECT LOWER(LAST_NAME ||' '|| FIRST_NAME) "Nombre Trabajador Minusculas",
	   UPPER(LAST_NAME ||' '|| FIRST_NAME) "Nombre Trabajador Mayusculas"
FROM EMPLOYEES
ORDER BY 1;
           
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE JOB_ID IN (
		SELECT JOB_ID
		FROM EMPLOYEES
		WHERE  SALARY IN (SELECT SALARY
							FROM EMPLOYEES
							WHERE SALARY BETWEEN 10000 AND 15000))
ORDER BY SALARY;

SELECT COUNT(*)
FROM employees
GROUP BY Employee_id
HAVING SALARY > 15000;

SELECT E.JOB_ID CVE_DEPTO, (SELECT J.JOB_TITLE
         FROM JOBS J
         WHERE J.JOB_ID = E.JOB_ID ) DEPARTAMENTO,
        SUM(E.SALARY) TOTAL_SALARIOS,
        AVG(E.SALARY) PROMEDIO_SALARIOS,
        COUNT(E.EMPLOYEE_ID) TRABAJADORES
FROM EMPLOYEES E
GROUP BY E.JOB_ID
ORDER BY 1;

Seleciona de 

SELECT E.JOB_ID, JOB_TITLE, "TOTAL EMPLEADOS",
       PROMEDIO_SALARIO, MIN_SALARY, MAX_SALARY
FROM JOBS J
LEFT JOIN (  SELECT JOB_ID, COUNT( EMPLOYEE_ID ) "TOTAL EMPLEADOS", 
             	SUM( SALARY ) SUMA_SALARIO ,
               	AVG( SALARY ) PROMEDIO_SALARIO
        	FROM EMPLOYEES
 			GROUP BY JOB_ID ) E 
ON J.JOB_ID = E.JOB_ID
ORDER by 6;




SELECT R.REGION_ID ID_REGION, REGION_NAME NOMBRE_REGION,CANTIDAD_PAISES
FROM REGIONS R
LEFT JOIN ( SELECT REGION_ID,
              COUNT( COUNTRY_NAME ) CANTIDAD_PAISES
    FROM COUNTRIES
    GROUP BY REGION_ID) C
ON R.REGION_ID = C.REGION_ID;

SELECT LAST_NAME||' '||FIRST_NAME EMPLEADO, 
JOBS.JOB_ID, JOB_TITLE PUESTO
FROM EMPLOYEES
LEFT JOIN
JOBS
ON EMPLOYEES.JOB_ID = JOBS.JOB_ID
WHERE JOBS.JOB_ID = ANY('ST_MAN', 'PR_REP', 'IT_PROG')



SELECT LOWER(LAST_NAME ||' '|| FIRST_NAME) "Nombre Trabajador Minusculas"
FROM EMPLOYEES
UNION
SELECT UPPER(LAST_NAME ||' '|| FIRST_NAME) "Nombre Trabajador Mayusculas"
FROM EMPLOYEES
ORDER BY 1;
           

SELECT LOWER(LAST_NAME ||' '|| FIRST_NAME) "Nombre Trabajador Minusculas",
	   UPPER(LAST_NAME ||' '|| FIRST_NAME) "Nombre Trabajador Mayusculas"
FROM EMPLOYEES
ORDER BY 1;


SELECT LAST_NAME, FIRST_NAME, (12*SALARY)*comission_pct "COMISION"
		NVL(COMISION_PCT,0)*(SALARY*12)
		FROM EMPLOYEES;

		INSERT INTO PRUEBAS_LOCAS
 VALUES (15, 'CLASE FINAL');
